language: python

matrix:
  include:
    - python: "2.7"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial
    - python: "3.8-dev"
      dist: xenial

before_install:
  # The debian package starts the server :/
  - echo exit 101 | sudo tee /usr/sbin/policy-rc.d
  - sudo chmod +x /usr/sbin/policy-rc.d
  - sudo apt-get -qq update
  - sudo apt-get install -y postgresql-9.6 postgresql-client-9.6

before_script:
  - export PATH=$PATH:/usr/lib/postgresql/9.6/bin
  - git submodule update --init

install:
  - "pip install -r requirements.txt -r buildrequirements.txt"

script: "python${TRAVIS_PYTHON_VERSION%%-dev} setup.py install --root `pwd` && make check TEST_PYTHONS=python${TRAVIS_PYTHON_VERSION%%-dev}"
